export const HISTORY_STOCKS_POLLING = 'HISTORY_STOCKS_POLLING';
export const NEXT_STOCKS_POLLING = 'NEXT_STOCKS_POLLING';
export const START_STOCKS_POLLING = 'START_STOCKS_POLLING';
export const PAUSE_STOCKS_POLLING = 'PAUSE_STOCKS_POLLING';
export const EDIT_STOCKS = 'EDIT_STOCKS';
